var lang_strings = {
  "en": {
    "title": "Cantonese Romanization Converter",
    "input": "Input romanized Cantonese here",
    "orig": "From:",
    "out": "To:",
    "result": "Result:",
    "convert": "Convert",
    "src": "Source",
    "py0": "Yale (numerals)",
    "py1": "Yale (diacritics)",
    "py2": "Cantonese Pinyin",
    "py3": "S. L. Wong (numerals)",
    "py4": "S. L. Wong (diacritics)",
    "py5": "IPA",
    "py6": "Jyutping",
    "py7": "Canton Romanization",
    "py8": "Sidney Lau",
    "py9": "Penkyamp (numerals)",
    "py10": "Penkyamp (diacritics)",
    "lang": "語言"
  },
  "zhs": {
    "title": "粤语拼音转换",
    "input": "输入粤语拼音",
    "orig": "原文：",
    "out": "转成：",
    "result": "结果：",
    "convert": "转换",
    "src": "原始码",
    "py0": "耶鲁拼音（数字）",
    "py1": "耶鲁拼音（调符）",
    "py2": "教院拼音",
    "py3": "黄锡凌（数字）",
    "py4": "黄锡凌（调符）",
    "py5": "国际音标",
    "py6": "粤拼",
    "py7": "广州拼音",
    "py8": "刘锡祥",
    "py9": "粤语拼音字（数字）",
    "py10": "粤语拼音字（调符）",
    "lang": "Language"
  },
  "zht": {
    "title": "粵語拼音轉換",
    "input": "輸入粵語拼音",
    "orig": "原文：",
    "out": "轉成：",
    "result": "結果：",
    "convert": "轉換",
    "src": "原始碼",
    "py0": "耶魯拼音（數字）",
    "py1": "耶魯拼音（調符）",
    "py2": "教院拼音",
    "py3": "黃錫凌（數字）",
    "py4": "黃錫凌（調符）",
    "py5": "國際音標",
    "py6": "粵拼",
    "py7": "廣州拼音",
    "py8": "劉錫祥",
    "py9": "粵語拼音字（數字）",
    "py10": "粵語拼音字（調符）",
    "lang": "Language"
  }
};
